### PR TITLE
Added Rust in UDL

### PR DESCRIPTION
**Pull request by Raghav-Bell**
Notepad++ does not support rust keywords color. I have added [Paolo Falabella rust style](https://github.com/pfalabella/Rust-notepadplusplus/blob/master/darkThemeCompatible.xml) file in UDL list.

### CODE REVIEW

**Comment by pryrt** [comment]
> Notepad++ does not support rust keywords color.

I'm not opposed to adding a Rust UDL to the UDL Repository.  However, Notepad++ natively supports Rust:
image
In fact, per the [Change List](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#75), it's supported Rust since Notepad++ v7.5 in 2017 - so for 6+ years now.

image

If what you really mean is that the _theme_ you are using doesn't have the definitions for Rust, that's not a big problem.  You can just copy over the "rust" portion of the default `stylers.xml` or another theme that already has Rust, and copy that section into your `themes\XXXX.xml`, and then restart Notepad++; after that, the XXXX theme will have a section on Rust, and you can set the colors using the GUI to whatever matches your current theme.

I just skimmed through the themes: the default `stylers.xml` and `themes\DarkModeDefault.xml` (maintained by the core developers), along with the `solarized.xml` and `zenburn.xml` themes, all include color definitions for Rust; but I didn't see it in any of the other themes.

Let me know if you still want to add the Rust UDL ... but I would think that just copying from another theme would give you the full benefits of the official Rust lexer, which likely does better than a UDL.

**Comment by Raghav-Bell** [comment]
@pryrt I mostly use deep black theme in that theme  default rust text highlighting is not supported (as shown). 

image

That's why googled and  i got only this answer [Adding Rust (programming language) syntax to Notepad++?](https://stackoverflow.com/questions/34435031/adding-rust-programming-language-syntax-to-notepad)
I don't have any problem with default rust or aforementioned UDL, i can work on both, thing is keyword higlighting helps in fast debugging . I think you can better decide the rest to add it or not 
Thanks.

**Comment by pryrt** [comment]
> I mostly use deep black theme

Then I'd probably suggest copying the "rust" section from DarkModeDefault.xml into DeepBlack.xml and then restart Notepad++, so that your copy of DeepBlack will have colors for Rust.  (And if you don't like the colors that it brought in, you could then use the GUI to set the colors).

> I think you can better decide the rest to add it or not

Okay, then I won't bother including the UDL version.

**Comment by rdipardo** [comment]
> I would think that just copying from another theme would give you the full benefits of the official Rust lexer, which likely does better than a UDL.

One exclusive feature of UDLs (for *any* language) is that consecutive *line comments* are folded; only a few Lexilla lexers do this, and Rust is not one of them:

| Lexilla | UDL |
| :---:  | :-: |
| rust-à-la-coral-reef | rust-à-la-udl |

> (And if you don't like the colors that it brought in, you could then use the GUI to set the colors).

@Raghav-Bell, you could also try the [dark theme](https://rdipardo.bitbucket.io/projects/coral-reef-theme/) I developed, which has a full complement of languages (incl. Rust, shown above on the left). It's hard for third-party themes to get wide distribution, and the [themes repo](https://github.com/notepad-plus-plus/nppThemes) looks pretty forlorn, so hosting it there wouldn't improve its visibility very much.

**Comment by pryrt** [comment]
> > I would think that just copying from another theme would give you the full benefits of the official Rust lexer, which likely does better than a UDL.
> 
> One exclusive feature of UDLs (for _any_ language) is that consecutive _line comments_ are folded; only a few Lexilla lexers do this, and Rust is not one of them

I did not know that.  It might be a feature that someone interested in such things could make at the Lexilla project. ;-)

But until then, I re-opened it so the checks would run: it looks like they failed.  @Raghav-Bell , the JSON you added needs a comma between the "author" and "homepage" fields.

> @Raghav-Bell, you could also try the [dark theme](https://rdipardo.bitbucket.io/projects/coral-reef-theme/) I developed, which has a full complement of languages (incl. Rust, shown above on the left). It's hard for third-party themes to get wide distribution, and the [themes repo](https://github.com/notepad-plus-plus/nppThemes) looks pretty forlorn, so hosting it there wouldn't improve its visibility very much.

If the author of the original [theme submission to the main application](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12038) had bothered to re-submit the theme to the Repo that we created for him, I probably would have taken the effort to make an announcement in the Community Forum, so it was more obvious, and maybe even add it to the User Manual (though no one reads that, either).  I put in the dummy theme, but it's an admittedly ugly theme whose only purpose was to populate that folder, since [Don said](https://github.com/notepad-plus-plus/nppThemes/pull/2#discussion_r962010710) I couldn't just copy the theme over from the original issue to the new repo.

If someone already had a fully-developed theme that they wanted to share (hint, hint), once it was in the repo, I might be re-encouraged to put time and effort into a Community post and mentioning it in the User Manual. ;-)

**Pull request merged**
