### PR TITLE
New SAS UDL for light and dark styles

### PR DESCRIPTION
**Pull request by prognase**
New SAS language UDL from scratch w/detailed list of keywords

- Keywords split into subject areas for optional style fine-tuning (info in XML file header)
- Code folding on PROC, Data Step, macro and multi-line comment level
- Does not interfere with user's default font family and size, uses background color transparency where applicable to allow none-black&white background color
- Includes versions for light and dark themes

### CODE REVIEW

**Comment by pryrt** [comment]
Need to fix errors

**Comment by prognase** [comment]
No idea what the conflict was / is. I am fairly new to GitHub, honestly first changes made. Usually on SVN and the like with other interface. Made a change, I think it is pending now.
Think I should check some more intros to GitHub to better understand the interface ;-)

**Comment by rdipardo** [comment]
@prognase,

> No idea what the conflict was / is.

Your UDL files are encoded in a single-byte character set, apparently [CP1252], the default on English and European editions of Windows. In Notepad++, the status bar shows "ANSI", which means the document's encoding is the same as the ["ANSI Code Page"] used by the operating system's character-handling functions:

ansi

Notice what happens to line 33 when you convert the encoding to Unicode (UTF-8):

unicode

You can also use a Python REPL to see how the single-byte ("ANSI") representation of `¬` and `¦` differs from the multi-byte (Unicode) representation:

~~~python
>>> bytes('¬ ¦', 'cp1252') # encode as CP1252, a.k.a. Windows-1252
b'\xac \xa6'

>>> bytes('¬ ¦', 'utf8')   # encode as UTF-8
b'\xc2\xac \xc2\xa6'
~~~

The Python validation script is doing exactly what you see above. The [`lxml.etree.parse()`] function reads your UDLs as a stream of bytes, and assumes they form a valid UTF-8 sequence. But no actual conversion to UTF-8 is done, so that assumption fails:

~~~python
>>> bytes('¬ ¦', 'cp1252').decode('utf8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte
~~~

You cannot feed a single-byte encoding of `¬` or `¦` to the Python script without an exception, unless you explicitly configure the script to treat your files as single-byte sequences. 

You need to fix the encoding of your UDL files. Save them as UTF-8, open them again in Notepad++, and replace the broken bytes with valid Unicode characters, i.e., using [`U+00AC`](https://www.fileformat.info/info/unicode/char/00ac/index.htm) for `¬` and [`U+00A6`](https://www.fileformat.info/info/unicode/char/00a6/index.htm) for `¦`.

[`lxml.etree.parse()`]: https://lxml.de/tutorial.html#the-parse-function
[CP1252]: https://en.wikipedia.org/wiki/Windows-1252#Codepage_layout
["ANSI Code Page"]: https://en.wikipedia.org/wiki/Windows_code_page#ANSI_code_page

**Comment by prognase** [comment]
I changed to UTF-8 and replaced content for the light and the dark XMLs - bit tricky on a MacBook w/o num pad area ;-)
image

And thanks for your detailed explanation, helped a lot!

**Pull request merged**
