### PR TITLE
Add requirements.txt and shebang line for python dependencies

### PR DESCRIPTION
**Pull request by nulLeeKH**

### CODE REVIEW

**Comment by chcg** [comment]
@nulLeeKH In appveyor.yml
requests jsonschema rfc3987 pywin32 lxml
are used for pip. Have you tested that rfc3987 pywin32 are not needed?

**Comment by chcg** [comment]
See https://blog.usejournal.com/why-and-how-to-make-a-requirements-txt-f329c685181e

**Comment by nulLeeKH** [comment]
Sorry. It's my mistake.
I think I accidentally erased several lines before I commit.

I will update this pull request.

**Review by chcg — APPROVED** [review]
ok

**Pull request merged**
