### PR TITLE
SQL_Manifold9_byRKolka: Few edits

### PR DESCRIPTION
**Pull request by rkolka**
Few edits to SQL_Manifold9_byRKolka.xml
Added some more samples

### CODE REVIEW

**Comment by pryrt** [comment]
Sorry if I merged the first version too early.
Let me know when you're done with modifications, and I'll merge the changes once you're done.

**Comment by pryrt** [comment]
Oh, wait, there are conflicts.  You'll have to fix those before I merge, or create a replacement branch and replacement PR that doesn't have conflicts.

**Comment by rkolka** [comment]
Thanks. I think it's a good thing that initial version got merged and public.
I have received feedback and I have still more tweaks coming in. 

Q: For Dark Mode, should this be another file in UDLs directory?  Then what aboud autoCompletions? Just identical copy with matching DarkMode filename?

**Comment by pryrt** [comment]
Yes, use a separate file for the Dark Mode UDL.  And since the UDL and autocompletion names must match, use a separate file for that, too.

**Comment by pryrt** [comment]
If you're still planning on coming back to this, let me know.  Otherwise, I am going to reject/close this PR in a day or two.

**Comment by rkolka** [comment]
You can close it. I hope to revisit this soon, but I can make a fresh PR anytime.

**Pull request closed without merging**
