### PR TITLE
add UDL Fobagraph script for laser machine + autocompletion

### PR DESCRIPTION
**Pull request by HelloWorldFR**
add 2 UDL Fobagraph script for laser machine: Light and Dark mode.
add autocompletion file

### CODE REVIEW

**Comment by pryrt** [comment]
Display name for the dark mode and light mode UDLs must be different.

**Comment by HelloWorldFR** [comment]
I change the name label. I need to make another pull request?
Best regard

**Comment by pryrt** [comment]
> I need to make another pull request? 

No need.  What you did made it into this one.

**Comment by HelloWorldFR** [comment]
Ok, thank

**Pull request merged**
