### PR TITLE
Dart UDL

### PR DESCRIPTION
**Pull request by thiagovscoelho**
I added a [Dart](https://dart.dev/) UDL. It looks like this:

image

### CODE REVIEW

**Comment by pryrt** [comment]
line #16 of your XML uses a token `&=`.  That is not valid inside an XML file.  It should be `&amp;=` .  Please fix

**Comment by thiagovscoelho** [comment]
Sure

**Comment by thiagovscoelho** [comment]
Oh, looks like the build failed because of a file extension thing. Let me see

**Comment by thiagovscoelho** [comment]
There we go, sorry about that

**Pull request merged**
