### PR TITLE
refined msc adams highlighting

### PR DESCRIPTION
**Pull request by alexander-recknagel**

### CODE REVIEW

**Comment by pryrt** [comment]
Please resolve conflicts, or this PR will have to be rejected.

**Comment by alexander-recknagel** [comment]
Hallo pryrt,

i did the conflict resolution and the checks passed. I thought that was enough? Could you please give a hint what else i need to do?
I am not that good at git/github yet :(

**Comment by pryrt** [comment]
I tried to replicate your changes -- I copied your updated `MSC-adams_car_by_ARRK.xml` file into a branch in my own fork, and when I created PR #70, it is willing to merge the file without conflicts.

I am not great at Git/GitHub conflict resolution (git does things "backwards" compared to the SVN that I am used to), so I think I'd prefer to incorporate the one that doesn't have conflicts.  Could you take a look at the file in #70 (https://github.com/notepad-plus-plus/userDefinedLanguages/blob/fdd48fa95ebac83d6395ba030832d9574af72d39/UDLs/MSC-adams_car_by_ARRK.xml) and make sure it's the same as what you think you're submitting.  Comment in #70 either way.

**Comment by pryrt** [comment]
For future reference:

On your fork and/or branch, there should be a **Fetch Upstream** button in modern GitHub website that looks like:
image
If you click on the **Fetch Upstream** and then **Fetch and Merge**, it will bring your fork/branch into sync with the official upstream repo (aka, "master").  By doing this before you make changes, the chances of conflicts during the merge are much reduced ... though if it's a long editing time after your fetch-and-merge, it may have new conflicts; in that case, doing another fetch-and-merge before creating your PR might help.  

(This is much easier in GitHub now than it was a few months back: before they added that button, you _had_ to do the merging/syncing in a git client on your machine, and had to know the right series of command-line-interface commands to get it to work.  Since the button has been added, I've had a lot less difficulty in interfacing with GitHub projects where someone else controls the upstream repo.)

**Comment by alexander-recknagel** [comment]
Thanks for the explanation. I will try it next time.

**Comment by pryrt** [comment]
replaced by #70

**Pull request closed without merging**
