### PR TITLE
Update REXX-SeveralDialects_byGertMassheimer.xml udlVersion 2.3

### PR DESCRIPTION
**Pull request by Kens390**
2024/04/04
	  Added Special Characters ": ;" to "Operators1"
		Not sure if users of this UDL like this change but its usually
		best practice to highlight statement terminator (i.e. semicolon).
	  Added Negator "^" to "Operators1"
	  Added Special Variables (RC, etc.)
	  Use "Keywords5" for Special Variables
		Used "keywords5" to allow customization of the style later.
	  Changed Style "Keywords5"
		Coded Style "Keywords5" with same style as "Keywords2" for now.
		Open to recommendations on what would be nice for this style.
          Corrected udlVersion back to 2.1

### CODE REVIEW

**Comment by pryrt** [comment]
Also, you just did a PR for this UDL, which I merged a few hours earlier.  Please make sure you have included _all_ your changes for this UDL in this PR.  I changed it to "Draft".  Please click "Ready for review" once you have made the changes I requested earlier, and have made sure you don't have any more that you want to change.

**Comment by Kens390** [comment]
Yes, I included all the changes. I increased the UDLVersion from 2.2 to 2.3
In comments you can see I included all the 2.2 updates within the 2.3

The compare that GitHub did this time was very unsatisfactory. If you pull the two sources and use Notepad++ to do a compare you would have better visibility into the changes.

Thank you for reviewing the change, I would not want to introduce preventable errors.

If you have any recommendations about the change please discuss.

I'll go update the pull request to "Ready to Review".

Ken Sharpe
Sr. Mainframe Systems Programmer, zVM and zLinux
o: 630.944.0799
m: 405.568.1919
e: ***@***.******@***.***>
Ensono.com<https://www.ensono.com/>


[A picture containing shape  Description automatically generated]
[in]<https://www.linkedin.com/company/ensono/>

[Tw]<https://twitter.com/ensonoit>

[FB]<https://www.facebook.com/EnsonoIT/>

PTO:

**Comment by Kens390** [comment]
Thanks for the advice. I did not know I would have additional changes. The nature of the changes in URLVersion 2.3 is a bit different from the prior fork I did (which focused on folding). This is all new to me so I am sure I could use advice like you are giving.

Ken Sharpe
Sr. Mainframe Systems Programmer, zVM and zLinux
o: 630.944.0799
m: 405.568.1919
e: ***@***.******@***.***>
Ensono.com<https://www.ensono.com/>


[A picture containing shape  Description automatically generated]
[in]<https://www.linkedin.com/company/ensono/>

[Tw]<https://twitter.com/ensonoit>

[FB]<https://www.facebook.com/EnsonoIT/>

PTO:

(c) 2021 Ensono, LP. All rights reserved. Ensono is a trademark of Ensono, LP. The information contained in this communication is confidential, is intended only for the use of the recipient named above, and may be legally privileged. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please resend this communication to the sender and delete the original message or any copy of it from your computer system.

**Comment by pryrt** [comment]
> The nature of the changes in URLVersion 2.3 is a bit different from the prior fork I did (which focused on folding)

You have misunderstood.  You should never have changed `udlVersion`.  It MUST be `udlVersion="2.1"`.  There is no other valid value, and you should never have changed that.  It is wrong now, because it says `udlVersion="2.3"`.  Please edit the file to fix it back to `udlVersion="2.1"` .  If you do not, this PR will be rejected.

**Comment by Kens390** [comment]
Sorry, yes, I did misunderstand. I did another commit on the #236 to resolve the problem with udlVersion.

Thanks,
Ken Sharpe
Sr. Mainframe Systems Programmer, zVM and zLinux
o: 630.944.0799
m: 405.568.1919
e: ***@***.******@***.***>
Ensono.com<https://www.ensono.com/>


[A picture containing shape  Description automatically generated]
[in]<https://www.linkedin.com/company/ensono/>

[Tw]<https://twitter.com/ensonoit>

[FB]<https://www.facebook.com/EnsonoIT/>

PTO:

(c) 2021 Ensono, LP. All rights reserved. Ensono is a trademark of Ensono, LP. The information contained in this communication is confidential, is intended only for the use of the recipient named above, and may be legally privileged. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please resend this communication to the sender and delete the original message or any copy of it from your computer system.

**Review by pryrt — APPROVED** [review]

**Pull request merged**
