### PR TITLE
added udl schema check via appveyor and github action

### PR DESCRIPTION
**Pull request by chcg**
@donho Do you prefer github actions https://github.com/chcg/userDefinedLanguages/commit/cff1c0d7a5c963cfefccc248819f77c6ab9ce914/checks?check_suite_id=397742873
 and/or appveyor https://ci.appveyor.com/project/chcg/userdefinedlanguages/builds/30075891
to check the udl. The schema check for the an empty repo or version is not working yet.
How do you think the check of a locally available udl vs. the one from the list should happen to see which one is newer? For plugins the dll version was used, but that is currently not possible for UDLs.

### CODE REVIEW

**Comment by donho** [comment]
@chcg 
`GitHub actions` is definitely cleaner to me. 

> The schema check for the an empty repo or verison is not working yet.
"repository" could be empty - it's an sensor for knowing if the UDL file is in our repository (ie. UDLs/ folder). The "version" is optional as well, because author may not wanna maintain it. But we can set this value as 1 by default.

> How do you think the check of a locally available udl vs. the one from the list should happen to see which one is newer?

For the moment, I'm not quite sure if UDL Admin is really necessary, so let's wait and see.

**Comment by chcg** [comment]
Ok. 
I will try to get the schema working also for empty entries.
And then go one with an udl xml schema check, if this is possible. I think I already did something similar to that.

**Comment by chcg** [comment]
@donho No it is working, see:
https://ci.appveyor.com/project/chcg/userdefinedlanguages/builds/30442517
and
https://github.com/chcg/userDefinedLanguages/actions/runs/32717299

**Comment by chcg** [comment]
@donho Should I merge it or will you do it?

**Comment by donho** [comment]
@chcg Please merge it.

**Pull request merged**
